apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: kubernetes-at-nnug-deployment
spec:
  selector:
    matchLabels:
      app: kubernetes-at-nnug
  replicas: 5
  template:
    metadata:
      labels:
        app: kubernetes-at-nnug
    spec:
      containers:
      - name: kubernetes-at-nnug
        image: kubernetes-at-nnug:v1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: kubernetes-at-nnug-service
  labels:
    app: kubernetes-at-nnug
spec:
  selector:
    app: kubernetes-at-nnug
  ports:
  - port: 80
    protocol: TCP
  type: LoadBalancer
